# Generated by Django 4.0.4 on 2022-04-23 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.FloatField()),
                ('loan_term_in_weeks', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('loan_emi', models.FloatField()),
                ('loan_emi_remaining', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_emi_paid', models.BooleanField(default=False)),
                ('loan_emi_due_date', models.DateField()),
                ('loan_emi_paid_on', models.DateField(blank=True, default=None, null=True)),
                ('laon_emi_amount', models.FloatField()),
                ('loan_emi_paid_amount', models.FloatField(blank=True, default=None, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanapplication')),
            ],
        ),
    ]
